### ISSUE TITLE
Connection failed for an unknown reason.

### ISSUE THREAD

**Issue by Thiefsie** [seansfkelley/nas-download-manager#209]
### Description

Connection failed for an unknown reason.
Was working fine yesterday no change.

### Steps to Reproduce the Issue
Try login

### Failure Logs
No such debug option 

### Versions

**Extension version**: 
0.12.0

**Browser version**: 
Google Chrome

Version 96.0.4664.45 (Official Build) (64-bit)

**DSM version**:
DSM 6.2.4-25556 Update 2

**Comment by Dedokta** [comment]
I'm having the same issue.

**Comment by maikerucouk** [comment]
Same, after an update to Download Station direct from Synology (if that helps)

**Comment by KirigayaShino** [comment]
I'm having the same issue.

**Comment by onestepforman** [comment]
I'm having the same issue.

**Comment by seansfkelley** [comment]
Given the timing and quantity of responses I'm guessing you were using HTTP, which I had to remove support for (see https://github.com/seansfkelley/nas-download-manager/issues/208).

Please let me know if that is not the case, and I can investigate further.

**Comment by jbimbo** [comment]
Hello,
I expérience this issue : 
You can see my settings for the app.
The problem seems to be that Chrome wich doesn't want to connect in https (see the adress bar when I'm connected to DSM) because of the certificate.
Is there anything to do ?

![2021-12-16_17h08_03](https://user-images.githubusercontent.com/95761706/146407157-bf237e4a-379e-4ffe-82e6-81f493dfb558.png)
![2021-12-16_17h12_18](https://user-images.githubusercontent.com/95761706/146407759-c7ee729a-e9f6-49f5-b2d7-2e1b741d18d2.png)

**Comment by seansfkelley** [comment]
Next time, try reading any of the documentation or the issues that were linked.

https://github.com/seansfkelley/nas-download-manager/blob/master/FAQ.md#what-is-an-invalid-certificate
